
from USPD_Frontend.Functionality_of_Device import Static_File_to_Page , Javascript_response , HTML_Page

handlers_frontend = {

    # # Основные файлы которые не изменяються
    "/http.js": Javascript_response,
    # # Файл иконки
    "/favicon.ico": Static_File_to_Page,

    #  Страницы - url
    "/": HTML_Page,
    "/meter_arch_month_cons": HTML_Page,
    "/meter_answ_jrnl": HTML_Page,
    "/meter_arch_day_cons": HTML_Page,
    "/meter_settings_routing": HTML_Page,
    "/meter_arch_hour": HTML_Page,
    "/sim_settings": HTML_Page,
    "/time_settings": HTML_Page,
    "/charge_station_state": HTML_Page,
    "/meter_jrnl_din": HTML_Page,
    "/meter_arch_month": HTML_Page,
    "/meter_arch_energy": HTML_Page,
    "/dout_state": HTML_Page,
    "/meter_arch_day": HTML_Page,
    "/meter_table": HTML_Page,
    "/meter_action_table": HTML_Page,
    "/meter_moment_energy": HTML_Page,
    "/meter_arch_din": HTML_Page,
    "/http_srv_settings": HTML_Page,
    "/meter_moment_quality": HTML_Page,
    "/time_jrnl": HTML_Page,
    "/charge_session_state": HTML_Page,
    "/meter_arch_cons": HTML_Page,
    "/mqtt_srv_settings": HTML_Page,
    "/event_manager_settings": HTML_Page,
    "/arch_template": HTML_Page,
    "/time": HTML_Page,
    "/sntp_settings": HTML_Page,
    "/meter_arch_quality": HTML_Page,
    "/meter_moment_din": HTML_Page,
    "/charge_process_state": HTML_Page,
    "/time_info_routing": HTML_Page,
    "/meter_moment_relay": HTML_Page,
    "/meter_arch_journal": HTML_Page,
    "/meter_template": HTML_Page,
    "/main": HTML_Page,
    "/charge_station_table": HTML_Page,
    "/modem_routing": HTML_Page,
    "/ip_settings": HTML_Page,
    "/meter_data_routing": HTML_Page,
    "/schdl_event_table": HTML_Page,
    "/os_diagn": HTML_Page,
    "/sync_actions_settings": HTML_Page,
    "/message_routing": HTML_Page,
    "/charge_station_routing": HTML_Page,
    "/net_routing": HTML_Page,
    "/mqtt_routing": HTML_Page,
    "/uart_settings": HTML_Page,
    "/meter_arch_config": HTML_Page,
    "/meter_moment_time": HTML_Page,
    "/update_firmware": HTML_Page,
    "/dout_settings": HTML_Page,
    "/meter_routing": HTML_Page,
    "/system_state": HTML_Page,
    "/dout_routing": HTML_Page,
    "/auth_settings": HTML_Page,

    #  Страницы - html

    # "meter_arch_month_cons.html": "meter_arch_month_cons.html",
    # "meter_answ_jrnl.html": "meter_answ_jrnl.html",
    # "meter_arch_day_cons.html": "meter_arch_day_cons.html",
    # "meter_settings_routing.html": "meter_settings_routing.html",
    # "meter_arch_hour.html": "meter_arch_hour.html",
    # "sim_settings.html": "sim_settings.html",
    # "time_settings.html": "time_settings.html",
    # "charge_station_state.html": "charge_station_state.html",
    # "meter_jrnl_din.html": "meter_jrnl_din.html",
    # "meter_arch_month.html": "meter_arch_month.html",
    # "meter_arch_energy.html": "meter_arch_energy.html",
    # "dout_state.html": "dout_state.html",
    # "meter_arch_day.html": "meter_arch_day.html",
    # "meter_table.html": "meter_table.html",
    # "meter_action_table.html": "meter_action_table.html",
    # "meter_moment_energy.html": "meter_moment_energy.html",
    # "meter_arch_din.html": "meter_arch_din.html",
    # "http_srv_settings.html": "http_srv_settings.html",
    # "meter_moment_quality.html": "meter_moment_quality.html",
    # "time_jrnl.html": "time_jrnl.html",
    # "charge_session_state.html": "charge_session_state.html",
    # "meter_arch_cons.html": "meter_arch_cons.html",
    # "mqtt_srv_settings.html": "mqtt_srv_settings.html",
    # "event_manager_settings.html": "event_manager_settings.html",
    # "arch_template.html": "arch_template.html",
    # "time.html": "time.html",
    # "sntp_settings.html": "sntp_settings.html",
    # "meter_arch_quality.html": "meter_arch_quality.html",
    # "meter_moment_din.html": "meter_moment_din.html",
    # "charge_process_state.html": "charge_process_state.html",
    # "time_info_routing.html": "time_info_routing.html",
    # "meter_moment_relay.html": "meter_moment_relay.html",
    # "meter_arch_journal.html": "meter_arch_journal.html",
    # "meter_template.html": "meter_template.html",
    # "main.html": "main.html",
    # "charge_station_table.html": "charge_station_table.html",
    # "modem_routing.html": "modem_routing.html",
    # "ip_settings.html": "ip_settings.html",
    # "meter_data_routing.html": "meter_data_routing.html",
    # "schdl_event_table.html": "schdl_event_table.html",
    # "os_diagn.html": "os_diagn.html",
    # "sync_actions_settings.html": "sync_actions_settings.html",
    # "message_routing.html": "message_routing.html",
    # "charge_station_routing.html": "charge_station_routing.html",
    # "net_routing.html": "net_routing.html",
    # "mqtt_routing.html": "mqtt_routing.html",
    # "uart_settings.html": "uart_settings.html",
    # "meter_arch_config.html": "meter_arch_config.html",
    # "meter_moment_time.html": "meter_moment_time.html",
    # "update_firmware.html": "update_firmware.html",
    # "dout_settings.html": "dout_settings.html",
    # "meter_routing.html": "meter_routing.html",
    # "system_state.html": "system_state.html",
    # "dout_routing.html": "dout_routing.html",
    # "auth_settings.html": "auth_settings.html",
}